version: '3'

volumes:
  pg_data:
  foodgram_static:
  foodgram_media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    container_name: foodgram-back
    image: villhard/foodgram-backend:latest
    platform: linux/amd64
    env_file: .env
    volumes:
      - foodgram_static:/backend_static/
      - foodgram_media:/app/media/
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    image: villhard/foodgram-frontend:latest
    platform: linux/amd64
    volumes:
      - foodgram_static:/app/result_build/

  gateway:
    container_name: foodgram-gate
    image: villhard/foodgram-gateway:latest
    platform: linux/amd64
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - foodgram_static:/staticfiles/
      - foodgram_media:/media/:ro
    depends_on:
      - backend
      - frontend